name: "qwen"
backend: "python"
max_batch_size: 16


input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

output [
  {
    name: "OUTPUT"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

instance_group [
  {
    kind: KIND_GPU,
	count: 1,
  }
]

dynamic_batching {}
